---
app:
  name: simplebank
  server:
    port: ${SERVER_PORT:7000}
  auth:
    service-shared-secret: ${SERVICE_SHARED_SECRET}
    ignorePaths: /info

spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
  database:
    driverClassName: org.postgresql
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    platform: postgres
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true