version: "3.7"

services:
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres-simple-bank-service
    labels:
      service_docker: "simple-bank-service"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres: